DROP TABLE IF EXISTS image;

CREATE TABLE image (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name VARCHAR(60) NOT NULL,
description VARCHAR(255),
url VARCHAR(255) NOT NULL
);

INSERT INTO image (id, name, url, description)
VALUES (1123123, 'One', 'https://i.pinimg.com/564x/17/78/c1/1778c168d724dc084002033f5b8b586c.jpg',
        'description 1');

INSERT INTO image (id, name, url, description)
VALUES (453431,  'Two', 'https://i.pinimg.com/564x/17/78/c1/1778c168d724dc084002033f5b8b586c.jpg',
        'description 2');

INSERT INTO image (id, name, url, description)
VALUES (511234,  'Three', 'https://i.pinimg.com/564x/17/78/c1/1778c168d724dc084002033f5b8b586c.jpg',
        'description 3');

INSERT INTO image (id, name, url, description)
VALUES (6423211,  'Four', 'https://i.pinimg.com/564x/17/78/c1/1778c168d724dc084002033f5b8b586c.jpg',
        'description 4');
